apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentsurveyform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentsurveyform
  template:
    metadata:
      labels:
        app: studentsurveyform
    spec:
      containers:
        - name: studentsurveyform
          image: sindhukodapa/studentsurveyform:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: studentsurveyform
spec:
  selector:
    app: studentsurveyform
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer